src/DemoProjectHost/Models/ErrorViewModel.cs
namespace DemoProject.UI.Host.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/DemoProjectHost/Controllers/HomeController.cs
using System.Diagnostics;
using DemoProject.UI.Host.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoProject.UI.Host.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/DemoProjectHost/Controllers/ProductsController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DemoProject.Application.Contracts;
using DemoProject.Application.Services;
using DemoProject.Domain.Notifications;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DemoProject.UI.Host.Controllers
{
    public class ProductsController: Controller
    {
        private readonly IProductService _productService;
	    private readonly DomainNotificationHandler _notifications;

	    public ProductsController(IProductService productService, INotificationHandler<DomainNotification> notifications)
	    {
		    _productService = productService;
		    _notifications = (DomainNotificationHandler)notifications;
	    }

        [HttpGet]
        [Route("products")]
        public async Task<IActionResult> Index()
        {
            return View(await _productService.GetAllAsync());
        }
		
		[HttpGet]
        [Route("products/export")]
        public async Task<IActionResult> Export()
        {
	        var exportedFile = await _productService.ExportAsync();

	        if (exportedFile == null || !exportedFile.Any())
	        {
		        return NotFound();
	        }
	        Stream exportStream = new MemoryStream(exportedFile);
	        return File(exportStream, "application/octet-stream", "products.xlsx");
        }
		
		[HttpPost]
        [Route("products/search")]
        public async Task<IActionResult> Search(string query)
        {
            return View("Index", await _productService.SearchAsync(query));
        }

        [HttpGet]
        [Route("products/{id:guid}/photo")]
        public async Task<IActionResult> Photo(Guid? id)
        {
	        if (id == null)
	        {
		        return NotFound();
	        }

            var photoBytes = await _productService.GetPhotoAsync(id.Value);

            if (photoBytes == null || !photoBytes.Any())
            {
                return NotFound();
            }
            Stream photoStream = new MemoryStream(photoBytes);
            return File(photoStream, "application/octet-stream");
        }
        
        [HttpGet]
        [Route("products/add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Route("products/add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Product product, IFormFile photo)
        {
	        if (!ModelState.IsValid)
	        {
		        return View(product);
	        }

	        //could be done via file streaming if we want to work with big files (above ~28Mb). But takes more time 
	        if (photo != null)
	        {
		        using (var ms = new MemoryStream())
		        {
			        photo.CopyTo(ms);
			        var fileBytes = ms.ToArray();
			        product.Photo = fileBytes;
		        }
	        }
			
            await _productService.AddAsync(product);

	        if (!_notifications.HasNotifications())
	        {
		        TempData["Success"] = $"Product '{product.Name}' added";
	        }

	        return RedirectToAction("Index");
        }
		
	    [HttpGet]
	    [Route("products/{id:guid}/details")]
	    public async Task<IActionResult> Details(Guid? id)
	    {
		    if (id == null)
		    {
			    return NotFound();
		    }

		    var product = await _productService.GetByIdAsync(id.Value);

		    if (product == null)
		    {
			    return NotFound();
		    }

		    return View(product);
	    }
		
		[HttpGet]
	    [Route("products/{id:guid}/edit")]
	    public async Task<IActionResult> Edit(Guid? id)
	    {
		    if (id == null)
		    {
			    return NotFound();
		    }

		    var product = await _productService.GetByIdAsync(id.Value);

		    if (product == null)
		    {
			    return NotFound();
		    }

		    return View(product);
	    }

	    [HttpPost]
	    [Route("products/{id:guid}/edit")]
	    [ValidateAntiForgeryToken]
	    public async Task<IActionResult> Edit(Product product, IFormFile photo)
	    {
		    if (!ModelState.IsValid)
		    {
			    return View(await _productService.GetByIdAsync(product.Id));
		    }

		    //could be done via file streaming if we want to work with big files (above ~28Mb). But takes more time 
		    if (photo != null)
		    {
			    using (var ms = new MemoryStream())
			    {
				    photo.CopyTo(ms);
				    var fileBytes = ms.ToArray();
				    product.Photo = fileBytes;
			    }
		    }

		    await _productService.EditAsync(product);

		    if (!_notifications.HasNotifications())
		    {
			    TempData["Success"] = "Product successfully edited.";
		    }

		    return View(await _productService.GetByIdAsync(product.Id));
	    }

	    [HttpGet]
	    [Route("products/{id:guid}/remove")]
	    public async Task<IActionResult> Delete(Guid? id)
	    {
		    if (id == null)
		    {
			    return NotFound();
		    }

		    var product = await _productService.GetByIdAsync(id.Value);

		    if (product == null)
		    {
			    return NotFound();
		    }

		    return View(product);
	    }

	    [HttpPost, ActionName("Delete")]
	    [Route("products/{id:guid}/remove")]
	    [ValidateAntiForgeryToken]
	    public async Task<IActionResult> RemoveConfirmed(Guid id)
	    {
		    await _productService.RemoveAsync(id);

		    if (_notifications.HasNotifications())
		    {
			    return View(await _productService.GetByIdAsync(id));
		    }

		    TempData["Success"] = "Product removed.";
		    return RedirectToAction("Index");
	    }
    }
}

src/DemoProjectHost/ViewComponents/SummaryViewComponent.cs
using System.Threading.Tasks;
using DemoProject.Domain.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace DemoProject.UI.Host.ViewComponents
{
	public class SummaryViewComponent : ViewComponent
	{
		private readonly DomainNotificationHandler _notifications;

		public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
		{
			_notifications = (DomainNotificationHandler)notifications;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var notifications = await Task.FromResult((_notifications.GetNotifications()));
			foreach (var domainNotification in notifications)
			{
				ViewData.ModelState.AddModelError(string.Empty, domainNotification.Value);
			}

			return View();
		}
	}
}

src/DemoProjectHost/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/DemoProjectHost/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/DemoProjectHost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/DemoProjectHost/Views/Products/Add.cshtml
@model DemoProject.Application.Contracts.Product

@{
    ViewData["Title"] = "Add new Product";
}

<h2>@ViewData["Title"]</h2>

<div id="confirmDialog" title="Save Student" hidden>
    <p>You entered price higher than 999,-</p>
    <p>Are you sure you want to save it?</p>
</div>


<form asp-action="Add" enctype="multipart/form-data" id="addProductForm">
    <div class="form-horizontal">
        <hr />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:summary />

        <div class="form-group">
            <label asp-for="Code" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Photo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Photo" type="file" class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
                <span>Max file size 28.6MiB</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnAdd" value="Add" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(function () {
        $("#btnAdd").click(function (e) {
            if ($("#Code-error").val() === undefined && $("#Name-error").val() === undefined && $("#Price-error").val() === undefined && $("#Price").val() > 999) {
                e.preventDefault();
                $("#confirmDialog").dialog("open");
            }
        });

        $("#confirmDialog").dialog({
            autoOpen: false,
            modal: true,
            resizable: false,
            buttons: {
                "Ok": function() {
                    $("#addProductForm").submit();
                },
                "Cancel": function(e) {
                    $(this).dialog("close");
                }
            }
        });
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/DemoProjectHost/Views/Products/Delete.cshtml
@model DemoProject.Application.Contracts.ProductReadmodel

@{
    ViewData["Title"] = "Delete Product";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Delete">
    <vc:summary />

    <h3>Are you sure you want to delete the @Model.Name?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Code)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Code)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt>
                <span>Product image</span>
            </dt>
            <dd>
                <img src="@Url.Action("Photo", new { id = Model.Id})" />
            </dd>
        </dl>


        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>

src/DemoProjectHost/Views/Products/Details.cshtml
@model DemoProject.Application.Contracts.ProductReadmodel

@{
    ViewData["Title"] = "Product Details";
}

<h2>@ViewData["Title"]</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>
        <dt>
            <span>Product image</span>
        </dt>
        <dd>
            <img src="@Url.Action("Photo", new { id = Model.Id})" />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

src/DemoProjectHost/Views/Products/Edit.cshtml
@model DemoProject.Application.Contracts.ProductReadmodel

@{
    ViewData["Title"] = "Edit Product";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <hr />
        
        <input type="hidden" asp-for="Id" />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:summary />

        <div class="form-group">
            <label asp-for="Code" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <label for="photo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input name="photo" id="photo" type="file" class="form-control" />
                <span>Max file size 28.6MiB</span>
            </div>
        </div>
        
        <img src="@Url.Action("Photo", new { id = Model.Id})" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/DemoProjectHost/Views/Products/Index.cshtml
@model IEnumerable<DemoProject.Application.Contracts.ProductReadmodel>

@{
    ViewData["Title"] = "Product catalog";
}

<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />

@* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
<vc:summary />

<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Add" class="btn btn-primary">
                    <span title="Add New" class="glyphicon glyphicon-plus-sign"></span> Add New
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Export" class="btn btn-primary">
                    <span title="Export" class="glyphicon glyphicon-export"></span> Export
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <form asp-action="Search">
                    <div class="row">
                        <div class="col-md-12">
                            <div>
                                <div class="pull-left">
                                    <input id="query" name="query" type="text"/>
                                    <input type="submit" value="Find" class="btn btn-success"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<br />

<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/DemoProjectHost/Views/Shared/Components/Summary/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="summaryMessage">Oops! Something went wrong:</h3>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
}

@if (!string.IsNullOrEmpty(TempData["Success"]?.ToString()))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="summaryMessage">@TempData["Success"]?.ToString()</h3>
    </div>
}

src/DemoProjectHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoProjectHost</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DemoProjectHost</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DemoProjectHost</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>